version: '3'

services:
  web:
    image: askapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: mysql:3306
      DB_HOST: mysql
      DB_NAME: askapp
      DJANGO_SECRET: askapp
      DB_USER: root
      DB_PASSWORD: askapp
      EMAIL_ADDRESS: askapp@askapp.com
      EMAIL_HOST: askapp
      EMAIL_HOST_PASSWORD: askapp
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.19
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: askapp
    restart: always

volumes:
  dbdata:
